// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.prabhatpandey.clipshot

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object ClipshotApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class ClipshotImageFormatMessage(val raw: Int) {
  JPEG(0),
  PNG(1);

  companion object {
    fun ofRaw(raw: Int): ClipshotImageFormatMessage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ClipshotRequest (
  val videoPath: String,
  val positionsMicroseconds: List<Long>,
  val maxWidth: Long? = null,
  val maxHeight: Long? = null,
  val quality: Long,
  val imageFormat: ClipshotImageFormatMessage,
  val outputDirectory: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ClipshotRequest {
      val videoPath = pigeonVar_list[0] as String
      val positionsMicroseconds = pigeonVar_list[1] as List<Long>
      val maxWidth = pigeonVar_list[2] as Long?
      val maxHeight = pigeonVar_list[3] as Long?
      val quality = pigeonVar_list[4] as Long
      val imageFormat = pigeonVar_list[5] as ClipshotImageFormatMessage
      val outputDirectory = pigeonVar_list[6] as String?
      return ClipshotRequest(videoPath, positionsMicroseconds, maxWidth, maxHeight, quality, imageFormat, outputDirectory)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      videoPath,
      positionsMicroseconds,
      maxWidth,
      maxHeight,
      quality,
      imageFormat,
      outputDirectory,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ClipshotRequest
    return ClipshotApiPigeonUtils.deepEquals(this.videoPath, other.videoPath) && ClipshotApiPigeonUtils.deepEquals(this.positionsMicroseconds, other.positionsMicroseconds) && ClipshotApiPigeonUtils.deepEquals(this.maxWidth, other.maxWidth) && ClipshotApiPigeonUtils.deepEquals(this.maxHeight, other.maxHeight) && ClipshotApiPigeonUtils.deepEquals(this.quality, other.quality) && ClipshotApiPigeonUtils.deepEquals(this.imageFormat, other.imageFormat) && ClipshotApiPigeonUtils.deepEquals(this.outputDirectory, other.outputDirectory)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ClipshotApiPigeonUtils.deepHash(this.videoPath)
    result = 31 * result + ClipshotApiPigeonUtils.deepHash(this.positionsMicroseconds)
    result = 31 * result + ClipshotApiPigeonUtils.deepHash(this.maxWidth)
    result = 31 * result + ClipshotApiPigeonUtils.deepHash(this.maxHeight)
    result = 31 * result + ClipshotApiPigeonUtils.deepHash(this.quality)
    result = 31 * result + ClipshotApiPigeonUtils.deepHash(this.imageFormat)
    result = 31 * result + ClipshotApiPigeonUtils.deepHash(this.outputDirectory)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ClipshotThumbnailMessage (
  val path: String,
  val requestedPositionMicroseconds: Long,
  val actualPositionMicroseconds: Long,
  val width: Long,
  val height: Long,
  val sizeBytes: Long,
  val imageFormat: ClipshotImageFormatMessage
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ClipshotThumbnailMessage {
      val path = pigeonVar_list[0] as String
      val requestedPositionMicroseconds = pigeonVar_list[1] as Long
      val actualPositionMicroseconds = pigeonVar_list[2] as Long
      val width = pigeonVar_list[3] as Long
      val height = pigeonVar_list[4] as Long
      val sizeBytes = pigeonVar_list[5] as Long
      val imageFormat = pigeonVar_list[6] as ClipshotImageFormatMessage
      return ClipshotThumbnailMessage(path, requestedPositionMicroseconds, actualPositionMicroseconds, width, height, sizeBytes, imageFormat)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      path,
      requestedPositionMicroseconds,
      actualPositionMicroseconds,
      width,
      height,
      sizeBytes,
      imageFormat,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ClipshotThumbnailMessage
    return ClipshotApiPigeonUtils.deepEquals(this.path, other.path) && ClipshotApiPigeonUtils.deepEquals(this.requestedPositionMicroseconds, other.requestedPositionMicroseconds) && ClipshotApiPigeonUtils.deepEquals(this.actualPositionMicroseconds, other.actualPositionMicroseconds) && ClipshotApiPigeonUtils.deepEquals(this.width, other.width) && ClipshotApiPigeonUtils.deepEquals(this.height, other.height) && ClipshotApiPigeonUtils.deepEquals(this.sizeBytes, other.sizeBytes) && ClipshotApiPigeonUtils.deepEquals(this.imageFormat, other.imageFormat)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ClipshotApiPigeonUtils.deepHash(this.path)
    result = 31 * result + ClipshotApiPigeonUtils.deepHash(this.requestedPositionMicroseconds)
    result = 31 * result + ClipshotApiPigeonUtils.deepHash(this.actualPositionMicroseconds)
    result = 31 * result + ClipshotApiPigeonUtils.deepHash(this.width)
    result = 31 * result + ClipshotApiPigeonUtils.deepHash(this.height)
    result = 31 * result + ClipshotApiPigeonUtils.deepHash(this.sizeBytes)
    result = 31 * result + ClipshotApiPigeonUtils.deepHash(this.imageFormat)
    return result
  }
}
private open class ClipshotApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ClipshotImageFormatMessage.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ClipshotRequest.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ClipshotThumbnailMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ClipshotImageFormatMessage -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is ClipshotRequest -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is ClipshotThumbnailMessage -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ClipshotHostApi {
  fun extractThumbnails(request: ClipshotRequest, callback: (Result<List<ClipshotThumbnailMessage>>) -> Unit)

  companion object {
    /** The codec used by ClipshotHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      ClipshotApiPigeonCodec()
    }
    /** Sets up an instance of `ClipshotHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ClipshotHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.clipshot.ClipshotHostApi.extractThumbnails$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ClipshotRequest
            api.extractThumbnails(requestArg) { result: Result<List<ClipshotThumbnailMessage>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ClipshotApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ClipshotApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
