// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsClipshotApi(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashClipshotApi(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsClipshotApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsClipshotApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsClipshotApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsClipshotApi(lhsKey, rhsKey) {
          if deepEqualsClipshotApi(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsClipshotApi(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashClipshotApi(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashClipshotApi(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashClipshotApi(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashClipshotApi(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashClipshotApi(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashClipshotApi(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


enum ClipshotImageFormatMessage: Int {
  case jpeg = 0
  case png = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct ClipshotRequest: Hashable {
  var videoPath: String
  var positionsMicroseconds: [Int64]
  var maxWidth: Int64? = nil
  var maxHeight: Int64? = nil
  var quality: Int64
  var imageFormat: ClipshotImageFormatMessage
  var outputDirectory: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ClipshotRequest? {
    let videoPath = pigeonVar_list[0] as! String
    let positionsMicroseconds = pigeonVar_list[1] as! [Int64]
    let maxWidth: Int64? = nilOrValue(pigeonVar_list[2])
    let maxHeight: Int64? = nilOrValue(pigeonVar_list[3])
    let quality = pigeonVar_list[4] as! Int64
    let imageFormat = pigeonVar_list[5] as! ClipshotImageFormatMessage
    let outputDirectory: String? = nilOrValue(pigeonVar_list[6])

    return ClipshotRequest(
      videoPath: videoPath,
      positionsMicroseconds: positionsMicroseconds,
      maxWidth: maxWidth,
      maxHeight: maxHeight,
      quality: quality,
      imageFormat: imageFormat,
      outputDirectory: outputDirectory
    )
  }
  func toList() -> [Any?] {
    return [
      videoPath,
      positionsMicroseconds,
      maxWidth,
      maxHeight,
      quality,
      imageFormat,
      outputDirectory,
    ]
  }
  static func == (lhs: ClipshotRequest, rhs: ClipshotRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsClipshotApi(lhs.videoPath, rhs.videoPath) && deepEqualsClipshotApi(lhs.positionsMicroseconds, rhs.positionsMicroseconds) && deepEqualsClipshotApi(lhs.maxWidth, rhs.maxWidth) && deepEqualsClipshotApi(lhs.maxHeight, rhs.maxHeight) && deepEqualsClipshotApi(lhs.quality, rhs.quality) && deepEqualsClipshotApi(lhs.imageFormat, rhs.imageFormat) && deepEqualsClipshotApi(lhs.outputDirectory, rhs.outputDirectory)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ClipshotRequest")
    deepHashClipshotApi(value: videoPath, hasher: &hasher)
    deepHashClipshotApi(value: positionsMicroseconds, hasher: &hasher)
    deepHashClipshotApi(value: maxWidth, hasher: &hasher)
    deepHashClipshotApi(value: maxHeight, hasher: &hasher)
    deepHashClipshotApi(value: quality, hasher: &hasher)
    deepHashClipshotApi(value: imageFormat, hasher: &hasher)
    deepHashClipshotApi(value: outputDirectory, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ClipshotThumbnailMessage: Hashable {
  var path: String
  var requestedPositionMicroseconds: Int64
  var actualPositionMicroseconds: Int64
  var width: Int64
  var height: Int64
  var sizeBytes: Int64
  var imageFormat: ClipshotImageFormatMessage


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ClipshotThumbnailMessage? {
    let path = pigeonVar_list[0] as! String
    let requestedPositionMicroseconds = pigeonVar_list[1] as! Int64
    let actualPositionMicroseconds = pigeonVar_list[2] as! Int64
    let width = pigeonVar_list[3] as! Int64
    let height = pigeonVar_list[4] as! Int64
    let sizeBytes = pigeonVar_list[5] as! Int64
    let imageFormat = pigeonVar_list[6] as! ClipshotImageFormatMessage

    return ClipshotThumbnailMessage(
      path: path,
      requestedPositionMicroseconds: requestedPositionMicroseconds,
      actualPositionMicroseconds: actualPositionMicroseconds,
      width: width,
      height: height,
      sizeBytes: sizeBytes,
      imageFormat: imageFormat
    )
  }
  func toList() -> [Any?] {
    return [
      path,
      requestedPositionMicroseconds,
      actualPositionMicroseconds,
      width,
      height,
      sizeBytes,
      imageFormat,
    ]
  }
  static func == (lhs: ClipshotThumbnailMessage, rhs: ClipshotThumbnailMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsClipshotApi(lhs.path, rhs.path) && deepEqualsClipshotApi(lhs.requestedPositionMicroseconds, rhs.requestedPositionMicroseconds) && deepEqualsClipshotApi(lhs.actualPositionMicroseconds, rhs.actualPositionMicroseconds) && deepEqualsClipshotApi(lhs.width, rhs.width) && deepEqualsClipshotApi(lhs.height, rhs.height) && deepEqualsClipshotApi(lhs.sizeBytes, rhs.sizeBytes) && deepEqualsClipshotApi(lhs.imageFormat, rhs.imageFormat)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ClipshotThumbnailMessage")
    deepHashClipshotApi(value: path, hasher: &hasher)
    deepHashClipshotApi(value: requestedPositionMicroseconds, hasher: &hasher)
    deepHashClipshotApi(value: actualPositionMicroseconds, hasher: &hasher)
    deepHashClipshotApi(value: width, hasher: &hasher)
    deepHashClipshotApi(value: height, hasher: &hasher)
    deepHashClipshotApi(value: sizeBytes, hasher: &hasher)
    deepHashClipshotApi(value: imageFormat, hasher: &hasher)
  }
}

private class ClipshotApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ClipshotImageFormatMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return ClipshotRequest.fromList(self.readValue() as! [Any?])
    case 131:
      return ClipshotThumbnailMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class ClipshotApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ClipshotImageFormatMessage {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? ClipshotRequest {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? ClipshotThumbnailMessage {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class ClipshotApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ClipshotApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ClipshotApiPigeonCodecWriter(data: data)
  }
}

class ClipshotApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = ClipshotApiPigeonCodec(readerWriter: ClipshotApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ClipshotHostApi {
  func extractThumbnails(request: ClipshotRequest, completion: @escaping (Result<[ClipshotThumbnailMessage], Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ClipshotHostApiSetup {
  static var codec: FlutterStandardMessageCodec { ClipshotApiPigeonCodec.shared }
  /// Sets up an instance of `ClipshotHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ClipshotHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let extractThumbnailsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.clipshot.ClipshotHostApi.extractThumbnails\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      extractThumbnailsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ClipshotRequest
        api.extractThumbnails(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      extractThumbnailsChannel.setMessageHandler(nil)
    }
  }
}
