name: clipshot
description: Extract still image frames from local video files on Android and iOS.
version: 0.1.0
homepage: https://prabhatpandey.com
repository: https://github.com/prabhatsdp/clipshot_flutter
issue_tracker: https://github.com/prabhatsdp/clipshot_flutter/issues

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.12.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  pigeon: ^26.1.4

flutter:
  plugin:
    platforms:
      android:
        package: com.prabhatpandey.clipshot
        pluginClass: ClipshotPlugin
      ios:
        pluginClass: ClipshotPlugin
